### PR TITLE
Re-focus cursor to ok button after display file's content.

### PR DESCRIPTION
**Pull request by ntdkhiem**
Making it easier for the user to add the file to the text editor.

Also, I don't know why my branch has 22 commits ahead of main.

### CODE REVIEW

**Comment by BoraxTheClean** [comment]
I'm getting some inconsistency with this. When I open a directory, sometimes it foucses on the `../` button, sometimes it focuses on `cancel`

**Comment by ntdkhiem** [comment]
I can re-focus the cursor to the `cancel `button instead of `../` button.

**Comment by BoraxTheClean** [comment]
> Making it easier for the user to add the file to the text editor.
> 
> Also, I don't know why my branch has 22 commits ahead of main.

After this gets merged run:
```
git checkout main
git pull
git branch -D scroll_menu
```

Typically you run into issues like this when you reuse one branch name for multiple features.

It won't cause any problems for this change, it just muddies the git history.

**Comment by BoraxTheClean** [comment]
> I can re-focus the cursor to the `cancel `button instead of `../` button.

My gripe was that it is inconsistent. Here is a Loom of me encountering this bug: https://www.loom.com/share/35cdc85571db4e16a5aa5287aeb6ff4e

Let me know if this is me doing something wrong?

**Comment by ntdkhiem** [comment]
I was able to re-produce this bug. I made it to always focuses on `../` button

**Review by BoraxTheClean — APPROVED** [review]

**Comment by BoraxTheClean** [comment]
@ntdkhiem Actually, should we update the docs for this change before you merge?

**Comment by ntdkhiem** [comment]
You meant this line? https://github.com/BoraxTheClean/adaptable-antelopes/blob/bd3c5ed9ad9699269d875f0c5f27c675803166fc/src/scroll/scroll_menu.py#L132

**Pull request merged**
