### PR TITLE
menu bar: text to emoji change

### PR DESCRIPTION
**Pull request by rishigian**
Code for changing text to emoji. Is not yet done.

### CODE REVIEW

**Comment by BoraxTheClean** [comment]
FYI, we are thinking of making this an automatic feature.

**Comment by ntdkhiem** [comment]
This is so cool!

**Review by ntdkhiem — APPROVED** [review]
Amazing work!

**Comment by ntdkhiem** [comment]
One issue is that after converting text to emoji, the cursor goes back to top-left corner. I will open a new issue for this.

**Pull request merged**
